:- dynamic distance/3.

distance('Agartala', 'Ahmedabad', 3305).
distance('Agartala', 'Bangalore', 3824).
distance('Agartala', 'Bhubaneshwar', 2286).
distance('Agartala', 'Bombay', 3593).
distance('Agartala', 'Calcutta', 1863).
distance('Agartala', 'Chandigarh', 2998).
distance('Agartala', 'Cochin', 4304).
distance('Agartala', 'Delhi', 2708).
distance('Agartala', 'Hyderabad', 3330).
distance('Agartala', 'Indore', 2891).
distance('Agartala', 'Jaipur', 2801).
distance('Agartala', 'Kanpur', 2281).
distance('Agartala', 'Lucknow', 2252).
distance('Agartala', 'Madras', 3493).
distance('Agartala', 'Nagpur', 2696).
distance('Agartala', 'Nasik', 3365).
distance('Agartala', 'Panjim', 3507).
distance('Agartala', 'Patna', 1681).
distance('Agartala', 'Pondicherry', 3661).
distance('Agartala', 'Pune', 3442).
distance('Agra', 'Ahmedabad', 878).
distance('Agra', 'Bangalore', 1848).
distance('Agra', 'Bhubaneshwar', 1578).
distance('Agra', 'Bombay', 1202).
distance('Agra', 'Calcutta', 1300).
distance('Agra', 'Chandigarh', 448).
distance('Agra', 'Cochin', 2278).
distance('Agra', 'Delhi', 200).
distance('Agra', 'Hyderabad', 1246).
distance('Agra', 'Indore', 591).
distance('Agra', 'Jaipur', 230).
distance('Agra', 'Kanpur', 290).
distance('Agra', 'Lucknow', 369).
distance('Agra', 'Madras', 2048).
distance('Agra', 'Nagpur', 770).
distance('Agra', 'Nasik', 1005).
distance('Agra', 'Panjim', 1715).
distance('Agra', 'Patna', 885).
distance('Agra', 'Pondicherry', 2210).
distance('Agra', 'Pune', 1214).
distance('Ahmedabad', 'Ahmedabad', -).
distance('Ahmedabad', 'Bangalore', 1490).
distance('Ahmedabad', 'Bhubaneshwar', 1697).
distance('Ahmedabad', 'Bombay', 552).
distance('Ahmedabad', 'Calcutta', 2068).
distance('Ahmedabad', 'Chandigarh', 1157).
distance('Ahmedabad', 'Cochin', 1845).
distance('Ahmedabad', 'Delhi', 911).
distance('Ahmedabad', 'Hyderabad', 1436).
distance('Ahmedabad', 'Indore', 442).
distance('Ahmedabad', 'Jaipur', 648).
distance('Ahmedabad', 'Kanpur', 1168).
distance('Ahmedabad', 'Lucknow', 1247).
distance('Ahmedabad', 'Madras', 1821).
distance('Ahmedabad', 'Nagpur', 965).
distance('Ahmedabad', 'Nasik', 504).
distance('Ahmedabad', 'Panjim', 1165).
distance('Ahmedabad', 'Patna', 1656).
distance('Ahmedabad', 'Pondicherry', 1818).
distance('Ahmedabad', 'Pune', 664).
distance('Allahabad', 'Ahmedabad', 1251).
distance('Allahabad', 'Bangalore', 1686).
distance('Allahabad', 'Bhubaneshwar', 1090).
distance('Allahabad', 'Bombay', 1457).
distance('Allahabad', 'Calcutta', 817).
distance('Allahabad', 'Chandigarh', 912).
distance('Allahabad', 'Cochin', 2216).
distance('Allahabad', 'Delhi', 650).
distance('Allahabad', 'Hyderabad', 1084).
distance('Allahabad', 'Indore', 803).
distance('Allahabad', 'Jaipur', 713).
distance('Allahabad', 'Kanpur', 193).
distance('Allahabad', 'Lucknow', 234).
distance('Allahabad', 'Madras', 2011).
distance('Allahabad', 'Nagpur', 608).
distance('Allahabad', 'Nasik', 1155).
distance('Allahabad', 'Panjim', 1419).
distance('Allahabad', 'Patna', 402).
distance('Allahabad', 'Pondicherry', 1077).
distance('Allahabad', 'Pune', 1364).
distance('Amritsar', 'Ahmedabad', 1356).
distance('Amritsar', 'Bangalore', 2496).
distance('Amritsar', 'Bhubaneshwar', 2224).
distance('Amritsar', 'Bombay', 1849).
distance('Amritsar', 'Calcutta', 1919).
distance('Amritsar', 'Chandigarh', 239).
distance('Amritsar', 'Cochin', 3163).
distance('Amritsar', 'Delhi', 445).
distance('Amritsar', 'Hyderabad', 1892).
distance('Amritsar', 'Indore', 1258).
distance('Amritsar', 'Jaipur', 706).
distance('Amritsar', 'Kanpur', 926).
distance('Amritsar', 'Lucknow', 939).
distance('Amritsar', 'Madras', 2688).
distance('Amritsar', 'Nagpur', 1416).
distance('Amritsar', 'Nasik', 1665).
distance('Amritsar', 'Panjim', 2237).
distance('Amritsar', 'Patna', 1531).
distance('Amritsar', 'Pondicherry', 2856).
distance('Amritsar', 'Pune', 1862).
distance('Asansol', 'Ahmedabad', 1842).
distance('Asansol', 'Bangalore', 2187).
distance('Asansol', 'Bhubaneshwar', 523).
distance('Asansol', 'Bombay', 2040).
distance('Asansol', 'Calcutta', 226).
distance('Asansol', 'Chandigarh', 1503).
distance('Asansol', 'Cochin', 2544).
distance('Asansol', 'Delhi', 1262).
distance('Asansol', 'Hyderabad', 1693).
distance('Asansol', 'Indore', 1394).
distance('Asansol', 'Jaipur', 1304).
distance('Asansol', 'Kanpur', 789).
distance('Asansol', 'Lucknow', 825).
distance('Asansol', 'Madras', 1857).
distance('Asansol', 'Nagpur', 1122).
distance('Asansol', 'Nasik', 1746).
distance('Asansol', 'Panjim', 2300).
distance('Asansol', 'Patna', 395).
distance('Asansol', 'Pondicherry', 2024).
distance('Asansol', 'Pune', 1955).
distance('Bangalore', 'Ahmedabad', 1490).
distance('Bangalore', 'Bangalore', -).
distance('Bangalore', 'Bhubaneshwar', 1538).
distance('Bangalore', 'Bombay', 1013).
distance('Bangalore', 'Calcutta', 1961).
distance('Bangalore', 'Chandigarh', 2296).
distance('Bangalore', 'Cochin', 512).
distance('Bangalore', 'Delhi', 2049).
distance('Bangalore', 'Hyderabad', 563).
distance('Bangalore', 'Indore', 1601).
distance('Bangalore', 'Jaipur', 2005).
distance('Bangalore', 'Kanpur', 1855).
distance('Bangalore', 'Lucknow', 1934).
distance('Bangalore', 'Madras', 331).
distance('Bangalore', 'Nagpur', 1078).
distance('Bangalore', 'Nasik', 1035).
distance('Bangalore', 'Panjim', 440).
distance('Bangalore', 'Patna', 2071).
distance('Bangalore', 'Pondicherry', 328).
distance('Bangalore', 'Pune', 826).
distance('Baroda', 'Ahmedabad', 119).
distance('Baroda', 'Bangalore', 1408).
distance('Baroda', 'Bhubaneshwar', 1604).
distance('Baroda', 'Bombay', 433).
distance('Baroda', 'Calcutta', 1937).
distance('Baroda', 'Chandigarh', 1181).
distance('Baroda', 'Cochin', 1763).
distance('Baroda', 'Delhi', 1151).
distance('Baroda', 'Hyderabad', 1127).
distance('Baroda', 'Indore', 379).
distance('Baroda', 'Jaipur', 789).
distance('Baroda', 'Kanpur', 1230).
distance('Baroda', 'Lucknow', 1311).
distance('Baroda', 'Madras', 1739).
distance('Baroda', 'Nagpur', 774).
distance('Baroda', 'Nasik', 457).
distance('Baroda', 'Panjim', 1158).
distance('Baroda', 'Patna', 1582).
distance('Baroda', 'Pondicherry', 1735).
distance('Baroda', 'Pune', 545).
distance('Bhopal', 'Ahmedabad', 523).
distance('Bhopal', 'Bangalore', 1148).
distance('Bhopal', 'Bhubaneshwar', 1162).
distance('Bhopal', 'Bombay', 778).
distance('Bhopal', 'Calcutta', 1495).
distance('Bhopal', 'Chandigarh', 988).
distance('Bhopal', 'Cochin', 1995).
distance('Bhopal', 'Delhi', 742).
distance('Bhopal', 'Hyderabad', 808).
distance('Bhopal', 'Indore', 191).
distance('Bhopal', 'Jaipur', 596).
distance('Bhopal', 'Kanpur', 585).
distance('Bhopal', 'Lucknow', 664).
distance('Bhopal', 'Madras', 1604).
distance('Bhopal', 'Nagpur', 352).
distance('Bhopal', 'Nasik', 605).
distance('Bhopal', 'Panjim', 1143).
distance('Bhopal', 'Patna', 1016).
distance('Bhopal', 'Pondicherry', 1772).
distance('Bhopal', 'Pune', 814).
distance('Bhubaneshwar', 'Ahmedabad', 1647).
distance('Bhubaneshwar', 'Bangalore', 1538).
distance('Bhubaneshwar', 'Bhubaneshwar', -).
distance('Bhubaneshwar', 'Bombay', 1679).
distance('Bhubaneshwar', 'Calcutta', 423).
distance('Bhubaneshwar', 'Chandigarh', 2026).
distance('Bhubaneshwar', 'Cochin', 1895).
distance('Bhubaneshwar', 'Delhi', 1713).
distance('Bhubaneshwar', 'Hyderabad', 1044).
distance('Bhubaneshwar', 'Indore', 1355).
distance('Bhubaneshwar', 'Jaipur', 1758).
distance('Bhubaneshwar', 'Kanpur', 1283).
distance('Bhubaneshwar', 'Lucknow', 1254).
distance('Bhubaneshwar', 'Madras', 1207).
distance('Bhubaneshwar', 'Nagpur', 830).
distance('Bhubaneshwar', 'Nasik', 1516).
distance('Bhubaneshwar', 'Panjim', 1455).
distance('Bhubaneshwar', 'Patna', 862).
distance('Bhubaneshwar', 'Pondicherry', 1375).
distance('Bhubaneshwar', 'Pune', 1587).
distance('Bombay', 'Ahmedabad', 552).
distance('Bombay', 'Bangalore', 1013).
distance('Bombay', 'Bhubaneshwar', 1678).
distance('Bombay', 'Bombay', -).
distance('Bombay', 'Calcutta', 2012).
distance('Bombay', 'Chandigarh', 1645).
distance('Bombay', 'Cochin', 1368).
distance('Bombay', 'Delhi', 1404).
distance('Bombay', 'Hyderabad', 729).
distance('Bombay', 'Indore', 589).
distance('Bombay', 'Jaipur', 1148).
distance('Bombay', 'Kanpur', 1278).
distance('Bombay', 'Lucknow', 1366).
distance('Bombay', 'Madras', 1344).
distance('Bombay', 'Nagpur', 849).
distance('Bombay', 'Nasik', 197).
distance('Bombay', 'Panjim', 584).
distance('Bombay', 'Patna', 1856).
distance('Bombay', 'Pondicherry', 1452).
distance('Bombay', 'Pune', 184).
distance('Calcutta', 'Ahmedabad', 2068).
distance('Calcutta', 'Bangalore', 1461).
distance('Calcutta', 'Bhubaneshwar', 423).
distance('Calcutta', 'Bombay', 2012).
distance('Calcutta', 'Calcutta', -).
distance('Calcutta', 'Chandigarh', 1721).
distance('Calcutta', 'Cochin', 2318).
distance('Calcutta', 'Delhi', 1474).
distance('Calcutta', 'Hyderabad', 1467).
distance('Calcutta', 'Indore', 1620).
distance('Calcutta', 'Jaipur', 1530).
distance('Calcutta', 'Kanpur', 1010).
distance('Calcutta', 'Lucknow', 1089).
distance('Calcutta', 'Madras', 1160).
distance('Calcutta', 'Nagpur', 1163).
distance('Calcutta', 'Nasik', 1849).
distance('Calcutta', 'Panjim', 974).
distance('Calcutta', 'Patna', 621).
distance('Calcutta', 'Pondicherry', 1798).
distance('Calcutta', 'Pune', 2058).
distance('Calicut', 'Ahmedabad', 1648).
distance('Calicut', 'Bangalore', 520).
distance('Calicut', 'Bhubaneshwar', 1923).
distance('Calicut', 'Bombay', 1171).
distance('Calicut', 'Calcutta', 2346).
distance('Calicut', 'Chandigarh', 2741).
distance('Calicut', 'Cochin', 222).
distance('Calicut', 'Delhi', 2494).
distance('Calicut', 'Hyderabad', 910).
distance('Calicut', 'Indore', 1998).
distance('Calicut', 'Jaipur', 2523).
distance('Calicut', 'Kanpur', 2260).
distance('Calicut', 'Lucknow', 2339).
distance('Calicut', 'Madras', 715).
distance('Calicut', 'Nagpur', 1483).
distance('Calicut', 'Nasik', 1193).
distance('Calicut', 'Panjim', 576).
distance('Calicut', 'Patna', 2476).
distance('Calicut', 'Pondicherry', 566).
distance('Calicut', 'Pune', 984).
distance('Chandigarh', 'Ahmedabad', 1157).
distance('Chandigarh', 'Bangalore', 2296).
distance('Chandigarh', 'Bhubaneshwar', 2026).
distance('Chandigarh', 'Bombay', 1645).
distance('Chandigarh', 'Calcutta', 1721).
distance('Chandigarh', 'Chandigarh', -).
distance('Chandigarh', 'Cochin', 1965).
distance('Chandigarh', 'Delhi', 248).
distance('Chandigarh', 'Hyderabad', 1693).
distance('Chandigarh', 'Indore', 1052).
distance('Chandigarh', 'Jaipur', 507).
distance('Chandigarh', 'Kanpur', 661).
distance('Chandigarh', 'Lucknow', 740).
distance('Chandigarh', 'Madras', 2489).
distance('Chandigarh', 'Nagpur', 1217).
distance('Chandigarh', 'Nasik', 1466).
distance('Chandigarh', 'Panjim', 2028).
distance('Chandigarh', 'Patna', 1332).
distance('Chandigarh', 'Pondicherry', 2657).
distance('Chandigarh', 'Pune', 1663).
distance('Cochin', 'Ahmedabad', 1845).
distance('Cochin', 'Bangalore', 512).
distance('Cochin', 'Bhubaneshwar', 1895).
distance('Cochin', 'Bombay', 1368).
distance('Cochin', 'Calcutta', 2318).
distance('Cochin', 'Chandigarh', 1965).
distance('Cochin', 'Cochin', -).
distance('Cochin', 'Delhi', 2718).
distance('Cochin', 'Hyderabad', 1090).
distance('Cochin', 'Indore', 1804).
distance('Cochin', 'Jaipur', 2745).
distance('Cochin', 'Kanpur', 2385).
distance('Cochin', 'Lucknow', 2572).
distance('Cochin', 'Madras', 687).
distance('Cochin', 'Nagpur', 1608).
distance('Cochin', 'Nasik', 1390).
distance('Cochin', 'Panjim', 798).
distance('Cochin', 'Patna', 2601).
distance('Cochin', 'Pondicherry', 530).
distance('Cochin', 'Pune', 1181).
distance('Coimbatore', 'Ahmedabad', 1669).
distance('Coimbatore', 'Bangalore', 333).
distance('Coimbatore', 'Bhubaneshwar', 1633).
distance('Coimbatore', 'Bombay', 1192).
distance('Coimbatore', 'Calcutta', 2057).
distance('Coimbatore', 'Chandigarh', 2669).
distance('Coimbatore', 'Cochin', 195).
distance('Coimbatore', 'Delhi', 2412).
distance('Coimbatore', 'Hyderabad', 912).
distance('Coimbatore', 'Indore', 1964).
distance('Coimbatore', 'Jaipur', 2369).
distance('Coimbatore', 'Kanpur', 2218).
distance('Coimbatore', 'Lucknow', 2297).
distance('Coimbatore', 'Madras', 426).
distance('Coimbatore', 'Nagpur', 1441).
distance('Coimbatore', 'Nasik', 1214).
distance('Coimbatore', 'Panjim', 800).
distance('Coimbatore', 'Patna', 2434).
distance('Coimbatore', 'Pondicherry', 410).
distance('Coimbatore', 'Pune', 1005).
distance('Delhi', 'Ahmedabad', 911).
distance('Delhi', 'Bangalore', 2049).
distance('Delhi', 'Bhubaneshwar', 1713).
distance('Delhi', 'Bombay', 1404).
distance('Delhi', 'Calcutta', 1474).
distance('Delhi', 'Chandigarh', 248).
distance('Delhi', 'Cochin', 2718).
distance('Delhi', 'Delhi', -).
distance('Delhi', 'Hyderabad', 1477).
distance('Delhi', 'Indore', 806).
distance('Delhi', 'Jaipur', 263).
distance('Delhi', 'Kanpur', 481).
distance('Delhi', 'Lucknow', 499).
distance('Delhi', 'Madras', 2243).
distance('Delhi', 'Nagpur', 971).
distance('Delhi', 'Nasik', 1220).
distance('Delhi', 'Panjim', 1782).
distance('Delhi', 'Patna', 1086).
distance('Delhi', 'Pondicherry', 2411).
distance('Delhi', 'Pune', 1417).
distance('Gwalior', 'Ahmedabad', 919).
distance('Gwalior', 'Bangalore', 1734).
distance('Gwalior', 'Bhubaneshwar', 1486).
distance('Gwalior', 'Bombay', 1085).
distance('Gwalior', 'Calcutta', 1224).
distance('Gwalior', 'Chandigarh', 462).
distance('Gwalior', 'Cochin', 1881).
distance('Gwalior', 'Delhi', 315).
distance('Gwalior', 'Hyderabad', 1132).
distance('Gwalior', 'Indore', 497).
distance('Gwalior', 'Jaipur', 351).
distance('Gwalior', 'Kanpur', 280).
distance('Gwalior', 'Lucknow', 359).
distance('Gwalior', 'Madras', 1928).
distance('Gwalior', 'Nagpur', 656).
distance('Gwalior', 'Nasik', 891).
distance('Gwalior', 'Panjim', 1467).
distance('Gwalior', 'Patna', 809).
distance('Gwalior', 'Pondicherry', 2096).
distance('Gwalior', 'Pune', 1100).
distance('Hubli', 'Ahmedabad', 1101).
distance('Hubli', 'Bangalore', 391).
distance('Hubli', 'Bhubaneshwar', 1620).
distance('Hubli', 'Bombay', 614).
distance('Hubli', 'Calcutta', 2032).
distance('Hubli', 'Chandigarh', 2101).
distance('Hubli', 'Cochin', 774).
distance('Hubli', 'Delhi', 1854).
distance('Hubli', 'Hyderabad', 486).
distance('Hubli', 'Indore', 1060).
distance('Hubli', 'Jaipur', 1060).
distance('Hubli', 'Kanpur', 1772).
distance('Hubli', 'Lucknow', 1851).
distance('Hubli', 'Madras', 683).
distance('Hubli', 'Nagpur', 995).
distance('Hubli', 'Nasik', 646).
distance('Hubli', 'Panjim', 190).
distance('Hubli', 'Patna', 1998).
distance('Hubli', 'Pondicherry', 653).
distance('Hubli', 'Pune', 437).
distance('Hyderabad', 'Ahmedabad', 1436).
distance('Hyderabad', 'Bangalore', 563).
distance('Hyderabad', 'Bhubaneshwar', 1044).
distance('Hyderabad', 'Bombay', 729).
distance('Hyderabad', 'Calcutta', 1467).
distance('Hyderabad', 'Chandigarh', 1693).
distance('Hyderabad', 'Cochin', 1090).
distance('Hyderabad', 'Delhi', 1447).
distance('Hyderabad', 'Hyderabad', -).
distance('Hyderabad', 'Indore', 999).
distance('Hyderabad', 'Jaipur', 1404).
distance('Hyderabad', 'Kanpur', 1253).
distance('Hyderabad', 'Lucknow', 1332).
distance('Hyderabad', 'Madras', 699).
distance('Hyderabad', 'Nagpur', 476).
distance('Hyderabad', 'Nasik', 754).
distance('Hyderabad', 'Panjim', 765).
distance('Hyderabad', 'Patna', 1469).
distance('Hyderabad', 'Pondicherry', 865).
distance('Hyderabad', 'Pune', 545).
distance('Imphal', 'Ahmedabad', 3240).
distance('Imphal', 'Bangalore', 3677).
distance('Imphal', 'Bhubaneshwar', 2139).
distance('Imphal', 'Bombay', 3446).
distance('Imphal', 'Calcutta', 1717).
distance('Imphal', 'Chandigarh', 2851).
distance('Imphal', 'Cochin', 4156).
distance('Imphal', 'Delhi', 2561).
distance('Imphal', 'Hyderabad', 3283).
distance('Imphal', 'Indore', 2744).
distance('Imphal', 'Jaipur', 2654).
distance('Imphal', 'Kanpur', 2134).
distance('Imphal', 'Lucknow', 2105).
distance('Imphal', 'Madras', 3326).
distance('Imphal', 'Nagpur', 2549).
distance('Imphal', 'Nasik', 3218).
distance('Imphal', 'Panjim', 3360).
distance('Imphal', 'Patna', 1534).
distance('Imphal', 'Pondicherry', 3614).
distance('Imphal', 'Pune', 3295).
distance('Indore', 'Ahmedabad', 442).
distance('Indore', 'Bangalore', 1601).
distance('Indore', 'Bhubaneshwar', 1355).
distance('Indore', 'Bombay', 589).
distance('Indore', 'Calcutta', 1620).
distance('Indore', 'Chandigarh', 1052).
distance('Indore', 'Cochin', 1804).
distance('Indore', 'Delhi', 806).
distance('Indore', 'Hyderabad', 999).
distance('Indore', 'Indore', -).
distance('Indore', 'Jaipur', 405).
distance('Indore', 'Kanpur', 689).
distance('Indore', 'Lucknow', 768).
distance('Indore', 'Madras', 1795).
distance('Indore', 'Nagpur', 445).
distance('Indore', 'Nasik', 414).
distance('Indore', 'Panjim', 1115).
distance('Indore', 'Patna', 1205).
distance('Indore', 'Pondicherry', 1963).
distance('Indore', 'Pune', 623).
distance('Jabalpur', 'Ahmedabad', 901).
distance('Jabalpur', 'Bangalore', 1335).
distance('Jabalpur', 'Bhubaneshwar', 1087).
distance('Jabalpur', 'Bombay', 1143).
distance('Jabalpur', 'Calcutta', 1167).
distance('Jabalpur', 'Chandigarh', 1046).
distance('Jabalpur', 'Cochin', 1885).
distance('Jabalpur', 'Delhi', 800).
distance('Jabalpur', 'Hyderabad', 733).
distance('Jabalpur', 'Indore', 859).
distance('Jabalpur', 'Jaipur', 845).
distance('Jabalpur', 'Kanpur', 543).
distance('Jabalpur', 'Lucknow', 584).
distance('Jabalpur', 'Madras', 1529).
distance('Jabalpur', 'Nagpur', 257).
distance('Jabalpur', 'Nasik', 943).
distance('Jabalpur', 'Panjim', 1088).
distance('Jabalpur', 'Patna', 736).
distance('Jabalpur', 'Pondicherry', 1697).
distance('Jabalpur', 'Pune', 1003).
distance('Jaipur', 'Ahmedabad', 648).
distance('Jaipur', 'Bangalore', 2005).
distance('Jaipur', 'Bhubaneshwar', 1758).
distance('Jaipur', 'Bombay', 1148).
distance('Jaipur', 'Calcutta', 1530).
distance('Jaipur', 'Chandigarh', 507).
distance('Jaipur', 'Cochin', 2745).
distance('Jaipur', 'Delhi', 263).
distance('Jaipur', 'Hyderabad', 1404).
distance('Jaipur', 'Indore', 405).
distance('Jaipur', 'Jaipur', -).
distance('Jaipur', 'Kanpur', 517).
distance('Jaipur', 'Lucknow', 598).
distance('Jaipur', 'Madras', 2200).
distance('Jaipur', 'Nagpur', 928).
distance('Jaipur', 'Nasik', 1248).
distance('Jaipur', 'Panjim', 2496).
distance('Jaipur', 'Patna', 1115).
distance('Jaipur', 'Pondicherry', 2368).
distance('Jaipur', 'Pune', 1371).
distance('Jamshedpur', 'Ahmedabad', 1225).
distance('Jamshedpur', 'Bangalore', 1690).
distance('Jamshedpur', 'Bhubaneshwar', 422).
distance('Jamshedpur', 'Bombay', 1916).
distance('Jamshedpur', 'Calcutta', 268).
distance('Jamshedpur', 'Chandigarh', 1602).
distance('Jamshedpur', 'Cochin', 2710).
distance('Jamshedpur', 'Delhi', 1356).
distance('Jamshedpur', 'Hyderabad', 1578).
distance('Jamshedpur', 'Indore', 1477).
distance('Jamshedpur', 'Jaipur', 1387).
distance('Jamshedpur', 'Kanpur', 867).
distance('Jamshedpur', 'Lucknow', 1121).
distance('Jamshedpur', 'Madras', 1629).
distance('Jamshedpur', 'Nagpur', 1102).
distance('Jamshedpur', 'Nasik', 1788).
distance('Jamshedpur', 'Panjim', 2229).
distance('Jamshedpur', 'Patna', 473).
distance('Jamshedpur', 'Pondicherry', 1797).
distance('Jamshedpur', 'Pune', 1997).
distance('Jullundur', 'Ahmedabad', 1285).
distance('Jullundur', 'Bangalore', 2416).
distance('Jullundur', 'Bhubaneshwar', 2413).
distance('Jullundur', 'Bombay', 1778).
distance('Jullundur', 'Calcutta', 1869).
distance('Jullundur', 'Chandigarh', 154).
distance('Jullundur', 'Cochin', 3082).
distance('Jullundur', 'Delhi', 375).
distance('Jullundur', 'Hyderabad', 1821).
distance('Jullundur', 'Indore', 1171).
distance('Jullundur', 'Jaipur', 891).
distance('Jullundur', 'Kanpur', 855).
distance('Jullundur', 'Lucknow', 868).
distance('Jullundur', 'Madras', 2617).
distance('Jullundur', 'Nagpur', 1354).
distance('Jullundur', 'Nasik', 1591).
distance('Jullundur', 'Panjim', 2146).
distance('Jullundur', 'Patna', 1460).
distance('Jullundur', 'Pondicherry', 2785).
distance('Jullundur', 'Pune', 1791).
distance('Kanpur', 'Ahmedabad', 1168).
distance('Kanpur', 'Bangalore', 1855).
distance('Kanpur', 'Bhubaneshwar', 1283).
distance('Kanpur', 'Bombay', 1278).
distance('Kanpur', 'Calcutta', 1010).
distance('Kanpur', 'Chandigarh', 661).
distance('Kanpur', 'Cochin', 2385).
distance('Kanpur', 'Delhi', 481).
distance('Kanpur', 'Hyderabad', 1253).
distance('Kanpur', 'Indore', 689).
distance('Kanpur', 'Jaipur', 517).
distance('Kanpur', 'Kanpur', -).
distance('Kanpur', 'Lucknow', 79).
distance('Kanpur', 'Madras', 2049).
distance('Kanpur', 'Nagpur', 777).
distance('Kanpur', 'Nasik', 1103).
distance('Kanpur', 'Panjim', 1813).
distance('Kanpur', 'Patna', 596).
distance('Kanpur', 'Pondicherry', 2217).
distance('Kanpur', 'Pune', 1312).
distance('Kolhapur', 'Ahmedabad', 911).
distance('Kolhapur', 'Bangalore', 484).
distance('Kolhapur', 'Bhubaneshwar', 1622).
distance('Kolhapur', 'Bombay', 426).
distance('Kolhapur', 'Calcutta', 2045).
distance('Kolhapur', 'Chandigarh', 1910).
distance('Kolhapur', 'Cochin', 934).
distance('Kolhapur', 'Delhi', 1664).
distance('Kolhapur', 'Hyderabad', 578).
distance('Kolhapur', 'Indore', 870).
distance('Kolhapur', 'Jaipur', 1518).
distance('Kolhapur', 'Kanpur', 1779).
distance('Kolhapur', 'Lucknow', 1858).
distance('Kolhapur', 'Madras', 910).
distance('Kolhapur', 'Nagpur', 1050).
distance('Kolhapur', 'Nasik', 456).
distance('Kolhapur', 'Panjim', 254).
distance('Kolhapur', 'Patna', 2047).
distance('Kolhapur', 'Pondicherry', 907).
distance('Kolhapur', 'Pune', 247).
distance('Lucknow', 'Ahmedabad', 1247).
distance('Lucknow', 'Bangalore', 1934).
distance('Lucknow', 'Bhubaneshwar', 1254).
distance('Lucknow', 'Bombay', 1366).
distance('Lucknow', 'Calcutta', 1089).
distance('Lucknow', 'Chandigarh', 740).
distance('Lucknow', 'Cochin', 2572).
distance('Lucknow', 'Delhi', 499).
distance('Lucknow', 'Hyderabad', 1332).
distance('Lucknow', 'Indore', 768).
distance('Lucknow', 'Jaipur', 598).
distance('Lucknow', 'Kanpur', 79).
distance('Lucknow', 'Lucknow', -).
distance('Lucknow', 'Madras', 2128).
distance('Lucknow', 'Nagpur', 856).
distance('Lucknow', 'Nasik', 1182).
distance('Lucknow', 'Panjim', 1883).
distance('Lucknow', 'Patna', 566).
distance('Lucknow', 'Pondicherry', 2296).
distance('Lucknow', 'Pune', 1391).
distance('Ludhiana', 'Ahmedabad', 1220).
distance('Ludhiana', 'Bangalore', 2358).
distance('Ludhiana', 'Bhubaneshwar', 2088).
distance('Ludhiana', 'Bombay', 1770).
distance('Ludhiana', 'Calcutta', 1783).
distance('Ludhiana', 'Chandigarh', 105).
distance('Ludhiana', 'Cochin', 3027).
distance('Ludhiana', 'Delhi', 310).
distance('Ludhiana', 'Hyderabad', 1756).
distance('Ludhiana', 'Indore', 1115).
distance('Ludhiana', 'Jaipur', 570).
distance('Ludhiana', 'Kanpur', 790).
distance('Ludhiana', 'Lucknow', 803).
distance('Ludhiana', 'Madras', 2552).
distance('Ludhiana', 'Nagpur', 1280).
distance('Ludhiana', 'Nasik', 1528).
distance('Ludhiana', 'Panjim', 2091).
distance('Ludhiana', 'Patna', 1395).
distance('Ludhiana', 'Pondicherry', 2720).
distance('Ludhiana', 'Pune', 1726).
distance('Madras', 'Ahmedabad', 1821).
distance('Madras', 'Bangalore', 331).
distance('Madras', 'Bhubaneshwar', 1207).
distance('Madras', 'Bombay', 1344).
distance('Madras', 'Calcutta', 1630).
distance('Madras', 'Chandigarh', 2489).
distance('Madras', 'Cochin', 687).
distance('Madras', 'Delhi', 2243).
distance('Madras', 'Hyderabad', 699).
distance('Madras', 'Indore', 1795).
distance('Madras', 'Jaipur', 2200).
distance('Madras', 'Kanpur', 2049).
distance('Madras', 'Lucknow', 2128).
distance('Madras', 'Madras', -).
distance('Madras', 'Nagpur', 1272).
distance('Madras', 'Nasik', 1366).
distance('Madras', 'Panjim', 909).
distance('Madras', 'Patna', 2096).
distance('Madras', 'Pondicherry', 168).
distance('Madras', 'Pune', 1157).
distance('Madurai', 'Ahmedabad', 1922).
distance('Madurai', 'Bangalore', 432).
distance('Madurai', 'Bhubaneshwar', 1687).
distance('Madurai', 'Bombay', 1458).
distance('Madurai', 'Calcutta', 2110).
distance('Madurai', 'Chandigarh', 2785).
distance('Madurai', 'Cochin', 326).
distance('Madurai', 'Delhi', 2539).
distance('Madurai', 'Hyderabad', 995).
distance('Madurai', 'Indore', 2091).
distance('Madurai', 'Jaipur', 2496).
distance('Madurai', 'Kanpur', 2345).
distance('Madurai', 'Lucknow', 2424).
distance('Madurai', 'Madras', 480).
distance('Madurai', 'Nagpur', 1568).
distance('Madurai', 'Nasik', 1467).
distance('Madurai', 'Panjim', 872).
distance('Madurai', 'Patna', 2561).
distance('Madurai', 'Pondicherry', 333).
distance('Madurai', 'Pune', 1238).
distance('Meerut', 'Ahmedabad', 1092).
distance('Meerut', 'Bangalore', 2072).
distance('Meerut', 'Bhubaneshwar', 1822).
distance('Meerut', 'Bombay', 1468).
distance('Meerut', 'Calcutta', 1497).
distance('Meerut', 'Chandigarh', 381).
distance('Meerut', 'Cochin', 2741).
distance('Meerut', 'Delhi', 66).
distance('Meerut', 'Hyderabad', 1470).
distance('Meerut', 'Indore', 815).
distance('Meerut', 'Jaipur', 327).
distance('Meerut', 'Kanpur', 537).
distance('Meerut', 'Lucknow', 453).
distance('Meerut', 'Madras', 2266).
distance('Meerut', 'Nagpur', 994).
distance('Meerut', 'Nasik', 1242).
distance('Meerut', 'Panjim', 1805).
distance('Meerut', 'Patna', 934).
distance('Meerut', 'Pondicherry', 2434).
distance('Meerut', 'Pune', 1440).
distance('Nagpur', 'Ahmedabad', 965).
distance('Nagpur', 'Bangalore', 1078).
distance('Nagpur', 'Bhubaneshwar', 830).
distance('Nagpur', 'Bombay', 849).
distance('Nagpur', 'Calcutta', 1163).
distance('Nagpur', 'Chandigarh', 1217).
distance('Nagpur', 'Cochin', 1608).
distance('Nagpur', 'Delhi', 971).
distance('Nagpur', 'Hyderabad', 476).
distance('Nagpur', 'Indore', 445).
distance('Nagpur', 'Jaipur', 928).
distance('Nagpur', 'Kanpur', 777).
distance('Nagpur', 'Lucknow', 856).
distance('Nagpur', 'Madras', 1272).
distance('Nagpur', 'Nagpur', -).
distance('Nagpur', 'Nasik', 700).
distance('Nagpur', 'Panjim', 1247).
distance('Nagpur', 'Patna', 993).
distance('Nagpur', 'Pondicherry', 1440).
distance('Nagpur', 'Pune', 909).
distance('Nasik', 'Ahmedabad', 504).
distance('Nasik', 'Bangalore', 1036).
distance('Nasik', 'Bhubaneshwar', 1516).
distance('Nasik', 'Bombay', 197).
distance('Nasik', 'Calcutta', 1849).
distance('Nasik', 'Chandigarh', 1466).
distance('Nasik', 'Cochin', 1390).
distance('Nasik', 'Delhi', 1220).
distance('Nasik', 'Hyderabad', 754).
distance('Nasik', 'Indore', 414).
distance('Nasik', 'Jaipur', 1246).
distance('Nasik', 'Kanpur', 1103).
distance('Nasik', 'Lucknow', 1182).
distance('Nasik', 'Madras', 1366).
distance('Nasik', 'Nagpur', 700).
distance('Nasik', 'Nasik', -).
distance('Nasik', 'Panjim', 701).
distance('Nasik', 'Patna', 1679).
distance('Nasik', 'Pondicherry', 1363).
distance('Nasik', 'Pune', 209).
distance('Panjim', 'Ahmedabad', 1165).
distance('Panjim', 'Bangalore', 440).
distance('Panjim', 'Bhubaneshwar', 1455).
distance('Panjim', 'Bombay', 584).
distance('Panjim', 'Calcutta', 974).
distance('Panjim', 'Chandigarh', 2028).
distance('Panjim', 'Cochin', 798).
distance('Panjim', 'Delhi', 1782).
distance('Panjim', 'Hyderabad', 765).
distance('Panjim', 'Indore', 1115).
distance('Panjim', 'Jaipur', 2496).
distance('Panjim', 'Kanpur', 1813).
distance('Panjim', 'Lucknow', 1883).
distance('Panjim', 'Madras', 909).
distance('Panjim', 'Nagpur', 1247).
distance('Panjim', 'Nasik', 701).
distance('Panjim', 'Panjim', -).
distance('Panjim', 'Patna', 1804).
distance('Panjim', 'Pondicherry', 739).
distance('Panjim', 'Pune', 501).
distance('Patna', 'Ahmedabad', 1656).
distance('Patna', 'Bangalore', 2071).
distance('Patna', 'Bhubaneshwar', 862).
distance('Patna', 'Bombay', 1856).
distance('Patna', 'Calcutta', 621).
distance('Patna', 'Chandigarh', 1332).
distance('Patna', 'Cochin', 2601).
distance('Patna', 'Delhi', 1086).
distance('Patna', 'Hyderabad', 1489).
distance('Patna', 'Indore', 1205).
distance('Patna', 'Jaipur', 1115).
distance('Patna', 'Kanpur', 595).
distance('Patna', 'Lucknow', 566).
distance('Patna', 'Madras', 2096).
distance('Patna', 'Nagpur', 993).
distance('Patna', 'Nasik', 1679).
distance('Patna', 'Panjim', 1804).
distance('Patna', 'Patna', -).
distance('Patna', 'Pondicherry', 2264).
distance('Patna', 'Pune', 1738).
distance('Pondicherry', 'Ahmedabad', 1818).
distance('Pondicherry', 'Bangalore', 328).
distance('Pondicherry', 'Bhubaneshwar', 1375).
distance('Pondicherry', 'Bombay', 1452).
distance('Pondicherry', 'Calcutta', 1798).
distance('Pondicherry', 'Chandigarh', 2657).
distance('Pondicherry', 'Cochin', 530).
distance('Pondicherry', 'Delhi', 2411).
distance('Pondicherry', 'Hyderabad', 867).
distance('Pondicherry', 'Indore', 1963).
distance('Pondicherry', 'Jaipur', 2368).
distance('Pondicherry', 'Kanpur', 2217).
distance('Pondicherry', 'Lucknow', 2296).
distance('Pondicherry', 'Madras', 168).
distance('Pondicherry', 'Nagpur', 1440).
distance('Pondicherry', 'Nasik', 1363).
distance('Pondicherry', 'Panjim', 739).
distance('Pondicherry', 'Patna', 2264).
distance('Pondicherry', 'Pondicherry', -).
distance('Pondicherry', 'Pune', 1154).
distance('Pune', 'Ahmedabad', 664).
distance('Pune', 'Bangalore', 826).
distance('Pune', 'Bhubaneshwar', 1587).
distance('Pune', 'Bombay', 184).
distance('Pune', 'Calcutta', 2058).
distance('Pune', 'Chandigarh', 1663).
distance('Pune', 'Cochin', 1181).
distance('Pune', 'Delhi', 1417).
distance('Pune', 'Hyderabad', 545).
distance('Pune', 'Indore', 623).
distance('Pune', 'Jaipur', 1371).
distance('Pune', 'Kanpur', 1312).
distance('Pune', 'Lucknow', 1391).
distance('Pune', 'Madras', 1157).
distance('Pune', 'Nagpur', 909).
distance('Pune', 'Nasik', 209).
distance('Pune', 'Panjim', 501).
distance('Pune', 'Patna', 1738).
distance('Pune', 'Pondicherry', 1154).
distance('Pune', 'Pune', -).
distance('Ranchi', 'Ahmedabad', 1781).
distance('Ranchi', 'Bangalore', 2098).
distance('Ranchi', 'Bhubaneshwar', 560).
distance('Ranchi', 'Bombay', 1816).
distance('Ranchi', 'Calcutta', 414).
distance('Ranchi', 'Chandigarh', 1480).
distance('Ranchi', 'Cochin', 2455).
distance('Ranchi', 'Delhi', 1214).
distance('Ranchi', 'Hyderabad', 1434).
distance('Ranchi', 'Indore', 1333).
distance('Ranchi', 'Jaipur', 1243).
distance('Ranchi', 'Kanpur', 723).
distance('Ranchi', 'Lucknow', 912).
distance('Ranchi', 'Madras', 1767).
distance('Ranchi', 'Nagpur', 958).
distance('Ranchi', 'Nasik', 1615).
distance('Ranchi', 'Panjim', 1630).
distance('Ranchi', 'Patna', 302).
distance('Ranchi', 'Pondicherry', 1935).
distance('Ranchi', 'Pune', 1675).
distance('Shillong', 'Ahmedabad', 2839).
distance('Shillong', 'Bangalore', 3242).
distance('Shillong', 'Bhubaneshwar', 1640).
distance('Shillong', 'Bombay', 3011).
distance('Shillong', 'Calcutta', 1281).
distance('Shillong', 'Chandigarh', 2416).
distance('Shillong', 'Cochin', 3599).
distance('Shillong', 'Delhi', 2126).
distance('Shillong', 'Hyderabad', 1309).
distance('Shillong', 'Indore', 2309).
distance('Shillong', 'Jaipur', 2229).
distance('Shillong', 'Kanpur', 1699).
distance('Shillong', 'Lucknow', 1670).
distance('Shillong', 'Madras', 2911).
distance('Shillong', 'Nagpur', 2114).
distance('Shillong', 'Nasik', 2800).
distance('Shillong', 'Panjim', 2925).
distance('Shillong', 'Patna', 1019).
distance('Shillong', 'Pondicherry', 3079).
distance('Shillong', 'Pune', 2860).
distance('Shimla', 'Ahmedabad', 1256).
distance('Shimla', 'Bangalore', 2395).
distance('Shimla', 'Bhubaneshwar', 2127).
distance('Shimla', 'Bombay', 1753).
distance('Shimla', 'Calcutta', 1839).
distance('Shimla', 'Chandigarh', 99).
distance('Shimla', 'Cochin', 3056).
distance('Shimla', 'Delhi', 365).
distance('Shimla', 'Hyderabad', 1812).
distance('Shimla', 'Indore', 1171).
distance('Shimla', 'Jaipur', 636).
distance('Shimla', 'Kanpur', 846).
distance('Shimla', 'Lucknow', 659).
distance('Shimla', 'Madras', 2588).
distance('Shimla', 'Nagpur', 1336).
distance('Shimla', 'Nasik', 1567).
distance('Shimla', 'Panjim', 2130).
distance('Shimla', 'Patna', 1434).
distance('Shimla', 'Pondicherry', 2759).
distance('Shimla', 'Pune', 1782).
distance('Surat', 'Ahmedabad', 263).
distance('Surat', 'Bangalore', 1264).
distance('Surat', 'Bhubaneshwar', 1579).
distance('Surat', 'Bombay', 301).
distance('Surat', 'Calcutta', 1912).
distance('Surat', 'Chandigarh', 1325).
distance('Surat', 'Cochin', 1593).
distance('Surat', 'Delhi', 1182).
distance('Surat', 'Hyderabad', 983).
distance('Surat', 'Indore', 607).
distance('Surat', 'Jaipur', 932).
distance('Surat', 'Kanpur', 1296).
distance('Surat', 'Lucknow', 1375).
distance('Surat', 'Madras', 1695).
distance('Surat', 'Nagpur', 749).
distance('Surat', 'Nasik', 262).
distance('Surat', 'Panjim', 913).
distance('Surat', 'Patna', 1742).
distance('Surat', 'Pondicherry', 1789).
distance('Surat', 'Pune', 412).
distance('Trivandrum', 'Ahmedabad', 2197).
distance('Trivandrum', 'Bangalore', 696).
distance('Trivandrum', 'Bhubaneshwar', 1953).
distance('Trivandrum', 'Bombay', 1376).
distance('Trivandrum', 'Calcutta', 2376).
distance('Trivandrum', 'Chandigarh', 3051).
distance('Trivandrum', 'Cochin', 218).
distance('Trivandrum', 'Delhi', 1950).
distance('Trivandrum', 'Hyderabad', 1261).
distance('Trivandrum', 'Indore', 2156).
distance('Trivandrum', 'Jaipur', 2782).
distance('Trivandrum', 'Kanpur', 2611).
distance('Trivandrum', 'Lucknow', 2690).
distance('Trivandrum', 'Madras', 748).
distance('Trivandrum', 'Nagpur', 1834).
distance('Trivandrum', 'Nasik', 1742).
distance('Trivandrum', 'Panjim', 792).
distance('Trivandrum', 'Patna', 2827).
distance('Trivandrum', 'Pondicherry', 622).
distance('Trivandrum', 'Pune', 1533).
distance('Varanasi', 'Ahmedabad', 1373).
distance('Varanasi', 'Bangalore', 1791).
distance('Varanasi', 'Bhubaneshwar', 968).
distance('Varanasi', 'Bombay', 1597).
distance('Varanasi', 'Calcutta', 695).
distance('Varanasi', 'Chandigarh', 1032).
distance('Varanasi', 'Cochin', 2331).
distance('Varanasi', 'Delhi', 745).
distance('Varanasi', 'Hyderabad', 1189).
distance('Varanasi', 'Indore', 925).
distance('Varanasi', 'Jaipur', 835).
distance('Varanasi', 'Kanpur', 315).
distance('Varanasi', 'Lucknow', 286).
distance('Varanasi', 'Madras', 1985).
distance('Varanasi', 'Nagpur', 713).
distance('Varanasi', 'Nasik', 1399).
distance('Varanasi', 'Panjim', 1524).
distance('Varanasi', 'Patna', 280).
distance('Varanasi', 'Pondicherry', 2153).
distance('Varanasi', 'Pune', 1459).
distance('Vijayawada', 'Ahmedabad', 1705).
distance('Vijayawada', 'Bangalore', 637).
distance('Vijayawada', 'Bhubaneshwar', 775).
distance('Vijayawada', 'Bombay', 973).
distance('Vijayawada', 'Calcutta', 1198).
distance('Vijayawada', 'Chandigarh', 1959).
distance('Vijayawada', 'Cochin', 1174).
distance('Vijayawada', 'Delhi', 1716).
distance('Vijayawada', 'Hyderabad', 269).
distance('Vijayawada', 'Indore', 1255).
distance('Vijayawada', 'Jaipur', 1660).
distance('Vijayawada', 'Kanpur', 1519).
distance('Vijayawada', 'Lucknow', 1598).
distance('Vijayawada', 'Madras', 432).
distance('Vijayawada', 'Nagpur', 742).
distance('Vijayawada', 'Nasik', 1428).
distance('Vijayawada', 'Panjim', 876).
distance('Vijayawada', 'Patna', 1664).
distance('Vijayawada', 'Pondicherry', 598).
distance('Vijayawada', 'Pune', 842).
distance('Vishakapatnam', 'Ahmedabad', 1815).
distance('Vishakapatnam', 'Bangalore', 1093).
distance('Vishakapatnam', 'Bhubaneshwar', 445).
distance('Vishakapatnam', 'Bombay', 1754).
distance('Vishakapatnam', 'Calcutta', 868).
distance('Vishakapatnam', 'Chandigarh', 2127).
distance('Vishakapatnam', 'Cochin', 1449).
distance('Vishakapatnam', 'Delhi', 1881).
distance('Vishakapatnam', 'Hyderabad', 599).
distance('Vishakapatnam', 'Indore', 1433).
distance('Vishakapatnam', 'Jaipur', 1838).
distance('Vishakapatnam', 'Kanpur', 1687).
distance('Vishakapatnam', 'Lucknow', 1765).
distance('Vishakapatnam', 'Madras', 762).
distance('Vishakapatnam', 'Nagpur', 910).
distance('Vishakapatnam', 'Nasik', 1596).
distance('Vishakapatnam', 'Panjim', 1206).
distance('Vishakapatnam', 'Patna', 1334).
distance('Vishakapatnam', 'Pondicherry', 930).
distance('Vishakapatnam', 'Pune', 1658).

